### ISSUE TITLE
KillSwitch

### ISSUE THREAD

**Issue by jboutros89** [azinchen/nordvpn#10]
Hello Mate,

First of all, thank you for your hard work. My question is: is there a kill switch? so in case the VPN disconnects, the other machine machine depending on this one will not access the 'normal' internet (Without VPN)?

Thank you

**Comment by niXta1** [comment]
> Hello Mate,
> 
> First of all, thank you for your hard work. My question is: is there a kill switch? so in case the VPN disconnects, the other machine machine depending on this one will not access the 'normal' internet (Without VPN)?
> 
> Thank you

It only allows traffic to go through the VPN connection, it won't be bypassed.

**Comment by azinchen** [comment]
> It only allows traffic to go through the VPN connection, it won't be bypassed.

I think, he asked about restarting the VPN connection.

> My question is: is there a kill switch? so in case the VPN disconnects, the other machine machine depending on this one will not access the 'normal' internet (Without VPN)?

First, all connection to Internet are disabled at all, except thru the VPN connection.
Second, I did not implement "killswitch" for the container because I think the VPN connection shall be controlled by container itself.

There are two options how to control the VPN connection.
First, pass ping options of openvpn daemon by defining it in `OPENVPN_OPTS` environment variable. Try to use `–inactive 3600 –ping 10 –ping-exit 60` parameters. This option checks the connection to VPN server only.
Second, there are several environment variables which might be used to check the Internet connectivity thru the VPN connection, `CHECK_CONNECTION_CRON` `CHECK_CONNECTION_URL` `CHECK_CONNECTION_ATTEMPTS` `CHECK_CONNECTION_ATTEMPT_INTERVAL`. For enabling this feature the `CHECK_CONNECTION_CRON` `CHECK_CONNECTION_URL` shall be set, try to set `*/10 * * * *` and `https://www.google.com;https://www.microsoft.com` to them.

**Comment by jboutros89** [comment]
Thank you, my whole goal is that i do not want the other machine to go through the internet directly in case the VPN is not connected.

It is clear now.
