### ISSUE TITLE
Allow connection to a specific server (or list of servers)

### ISSUE THREAD

**Issue by noggl** [azinchen/nordvpn#139]
I migrated to this container from the bubuntux one, where I was using NordVPN's Dedicated IP OpenVPN Servers to host some services. As far as I have found, it is not possible to specify a specific server with this container, the closest I can get is specifying

`      - GROUP=legacy_dedicated_ip
      - TECHNOLOGY=openvpn_dedicated_udp`

However, this still gives a list of servers and will connect to the "best" available one. This means that the IP of my services change when restarting the container, which I do not want. Is there any way to specify the exact server to connect to (ex. us4956), or at least a list so that I know it is one of 3 IPs?

Thank you for your work on this container!

**Comment by azinchen** [comment]
No, there is not possible to specify the exact server or servers list. The main idea of `azinchen/nordvpn` image is to work with pool of NordVPN servers and select the best server. I'm happy that you choose `azinchen/nordvpn` image, but if you want to connect to exact server you should use another great docker image - `dperson/openvpn-client`.

I can help you with constructing .ovpn file if you need, but I don't think that 'specifying server' feature should be added to `azinchen/nordvpn` because it just duplicates functionality of `dperson/openvpn-client`.

**Comment by noggl** [comment]
Hello,

I have since tested the dperson/openvpn-client container again and found that it lacks support for the Dedicated IP servers provided by Nord VPN. This functionality is only available in a container that uses the official Nord VPN software like this container does, so I would like to ask again that this feature be considered.

Thank you
