### ISSUE TITLE
Username and PW login now disabled

### ISSUE THREAD

**Issue by Mateotey** [azinchen/nordvpn#367]
Can we pass on token instead?

NordVPN 3.16.2

Logging in with a username and password is no longer available in the terminal as we’ve switched to more secure login options.

**Comment by jfcabral** [comment]
Hi, I've just had this issue but solved it following this suggestion https://github.com/azinchen/nordvpn/issues/361#issuecomment-1612529369

Basically you now need to get a `service credential`, in order to authenticate:

1. Browse https://my.nordaccount.com/dashboard/
2. Services > NordVPN
3. Scroll down to Manual setup > Set up NordVPN manually
4. Verify your email
5. Obtain the service user and pass
6. Change the container configurations to use these `Service credentials` instead of your account ones

**Comment by Mateotey** [comment]
We just did that as well — thanks for the advice for others and help!
