### ISSUE TITLE
Having trouble finding the logs

### ISSUE THREAD

**Issue by so7ow** [azinchen/nordvpn#382]
On my old Synology/Docker setup the NordVPN logs were right there in the GUI. After moving to a Ubuntu Server setup and using Docker Compose, I'm not having any luck finding those NordVPN logs. Can anyone point me in the right direction? Do I need to mount a particular volume to get access to them easily?

**Comment by sservaes** [comment]
Would you mind sharing your docker compose file itself?
As you mention that the 'logs were right there in the GUI', I'm thinking that you are referring to the output that was printed in a running docker container. Since you are using docker compose to get the docker container up and running, you would have to enter the docker container to see the output printed within the docker's terminal.
Alternatively, if your goal is to store the output in an actual file, you would have to redirect the standard output to be stored in a (mounted) volume using docker's logging options.
More info for logging you can find [here](https://docs.docker.com/config/containers/logging/).

**Comment by so7ow** [comment]
Thanks for the reply. Yes, the answer was as simple as running `docker logs <container>`.
