### ISSUE TITLE
Debian9 - Ethernet configuration does not match

### ISSUE THREAD

**Issue by ShadoWarrior59** [azinchen/nordvpn#5]
Hello,

I try to use this docker with a debian 9.
The problem is that debian 9 does not use eth0 as main ethernet configuration interface but it uses enp3s0

Log :
Device "eth0" does not exist.
Bad argument `ACCEPT'
Try `iptables -h' or 'iptables --help' for more information.
Device "eth0" does not exist.

**Comment by GourouLubrik** [comment]
I run it with similar condition and got no error.
I'm on Open Media Vault, based on debian 9.
I got multiple Ethernet card, but no eth0.
I just did a docker-compose pull and restarted but it works.

Did you add the /dev/net volume ?

**Comment by ShadoWarrior59** [comment]
Thanks for your reply.
That's great I'm also using OMV on debian 9.
Attached the screen shots of how I've configured the docker.
And each time I launched the docker, it removes a line in iptables and I have to recreate it :
iptables -I OUTPUT 4 -p all -o enp3s0 -j ACCEPT
![conf_1](https://user-images.githubusercontent.com/48249704/53841129-511fd700-3f9c-11e9-9a95-b1291f08e5de.jpg)
![conf_2](https://user-images.githubusercontent.com/48249704/53841130-511fd700-3f9c-11e9-9c19-db5e91775293.jpg)
![conf_3](https://user-images.githubusercontent.com/48249704/53841131-51b86d80-3f9c-11e9-9f5a-0ba2cef92642.jpg)
![img_1](https://user-images.githubusercontent.com/48249704/53841132-51b86d80-3f9c-11e9-9536-c4f20541d3e0.jpg)

**Comment by GourouLubrik** [comment]
Hello fellow french compatriot 🇫🇷

I think your problem is that you use Host networking and that this image hasn't been tailored for that.
I don't use OMV docker interface, I find it simpler to use raw docker compose files.

As long as your using bridge networking or  macvlan, the ethernet name inside docker is eth0.
By using host network mode, you're exposing your real networks cards into docker.

I don't get the point of trying host networking, as ALL your OMV traffic would go through nordvpn. I think it's unlikely you really want with plex, as you cannot have port forwarding on nordvpn.

`
vpnclient:
    cap_add:
    - net_admin
    container_name: vpnclient
    dns:
    - 8.8.8.8
    - 8.8.4.4
    environment:
      CATEGORY: P2P
      COUNTRY: France
      NETWORK: 192.168.0.0/23
      PASS: PASSWORD
      PROTOCOL: openvpn_udp
      TZ: Europe/Paris
      USER: USERNAME
    expose:
    - 8112
    - 22
    - 3389
    image: azinchen/nordvpn
    networks:
      macnet0:
        ipv4_address: 192.168.0.210
    restart: unless-stopped
    security_opt:
    - label:disable
    stdin_open: true
    tmpfs:
    - /tmp
    tty: true
    volumes:
    - /dev/net:/dev/net:z
`
The macnet0 is an external network using macvlan driver to use a dedicated IP in my Lan environment (192.168.0.0/23 network), so I can connect to associated service using a real world ip without depending on NAT on a single ip already crowded by other services.

My other docker-compose that use nordvpn use this as `network_mode: "container:vpnclient"`
Thought it may fail upstart because of broken dependancies, it's easier to pull them all in the same docker-compose and use "depends_on" to avoid this.

If you really want to use network_mode: host, I guess you need more help that I can offer.

I guess the network name could be an .env variable and script that use network device name generated dynamically through sed or a template system ?

Any thoughts about this @azinchen ?

**Comment by azinchen** [comment]
I agree, it is a bad idea to use Host networking with any VPN client images. VPN client creates own network environment, and it would be better to isolate it. (by setting Bridge networking).

**Comment by azinchen** [comment]
> The macnet0 is an external network using macvlan driver to use a dedicated IP in my Lan environment (192.168.0.0/23 network), so I can connect to associated service using a real world ip without depending on NAT on a single ip already crowded by other services.

It works Ok without macvlan on my server. Exclude 'networks' section at all from your compose file and change 'expose' section to 'ports'.

**Comment by GourouLubrik** [comment]
I use macvlan on purpose because I prefer to organise my container that way for stuff that I don't wan't to NAT. 
It also let me use my VPN containers as a router without a proxy with other computers ;)

**Comment by ShadoWarrior59** [comment]
OK I've tried Bridge networking and all is ok now.
Thank you very much guys for the help from France :) 
Sorry but I'm not used to docker.
